app/__init__.py
from flask import Flask
from config import Config
from config import enviro
from flask_mail import Mail

mail = Mail()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    app.secret_key = enviro.get("SECRET_KEY")
    mail.init_app(app)

    from app.views.main import main
    app.register_blueprint(main)

    return app

app/views/main.py
from flask import request, redirect, render_template, url_for, session, Blueprint, json, jsonify
from app import mail
from flask_mail import Message

main = Blueprint('main', __name__)

@main.route("/")
def index():
    return render_template("index.html")

@main.route("/About")
def about():
    return render_template("about.html")

@main.route("/Contact")
def contact():
    return render_template("contact.html")

@main.route("/Send-contact", methods=["POST", "GET"])
def sendcontact():

    data = request.form.to_dict()

    msg = Message(
        'A potencional customer is trying to contact you.',
        sender='Management',
        recipients=["ph.julianrd@gmail.com"]
    )

    # with current_app.open_resource("static/img/RealmFly/Vertical Realm Logo.png") as fp:
    #     msg.attach("static/img/RealmFly/Vertical Realm Logo.png", "image/png",
    #                fp.read(), 'inline', headers=[['Content-ID', '<logo>'], ])

    # with current_app.open_resource("static/img/Email/email_white.png") as fp:
    #     msg.attach("static/img/Email/email_white.png", "image/png",
    #                fp.read(), 'inline', headers=[['Content-ID', '<email_icon>'], ])

    # Email template
    msg.html = render_template(
        'email.html', User = "ph.julianrd@gmail.com", email_data = data)

    try:
        mail.send(msg)
        status = True        
    except Exception as e:
        status = False        
    
    if status == True:
        response = "SENDING"
    else:
        response = "ERROR"

    return response

app/templates/about.html
{% extends "base.html" %}

{% block navbar %}
    <!-- nav -->
    <nav class="navbar navbar-default navbar-fixed-top" style="background-color: #000;">
        <div class="container">
            <div class="navbar-header"> 
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- LOGO -->
                <a class="navbar-brand" href="#">JULIAN RODRIGUEZ</a>

            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('main.index') }}" class="smooth_scroll">Home</a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.about') }}" class="smooth_scroll">About</a>
                    </li>                        
                    <li>
                        <a href="{{ url_for('main.contact') }}" class="smooth_scroll">Contact</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!--.container-->
    </nav>
{% endblock %}

{% block content %}
    <!--Start About Section-->
    <section class="about padding-top-90 padding-bottom-90" id="about">
        <div class="container">
            <div class="row">
                <div class="col-md-5 about-img">
                    <div class="my__img animated animated_scroll fadeInUp" style="animation-delay: 0.3s">
                        <img src="{{ url_for('static', filename = 'images/profile.jpg') }}" alt="">
                    </div>
                </div>
                <div class="col-md-7 padding-left-35">
                    <h3 class="animated animated_scroll fadeInUp" style="animation-delay: 0.3s">Hi There! I am Julian Rodriguez</h3>
                    <p class="animated animated_scroll fadeInUp" style="animation-delay: 0.3s">I'm 19 years old Photographer,musician, audio and video producer. I live in the United States and have been working for more than 3 years with photography and music. </p>
                    <p class="animated animated_scroll fadeInUp" style="animation-delay: 0.3s">
                        I perform very well in what I do, I focus on the perfection and detail of the projects that I own. I also strive to make an excellent mark on the world with my work.
                    </p>

                    <!-- Skills -->
                    <div class="skills">

                        <!--skill 1-->
                        <div class="skill">
                            <span>PHOTOGRAPHY</span>
                            <span>98%</span>
                            <div class="progress_bg">
                                <div class="progress_bar"></div>
                            </div>
                        </div>

                        <!--skill 2-->
                        <div class="skill">
                            <span>EDITION</span>
                            <span>95%</span>
                            <div class="progress_bg">
                                <div class="progress_bar"></div>
                            </div>
                        </div>

                        <!--skill 3-->
                        <div class="skill">
                            <span>RELIABILITY</span>
                            <span>100%</span>
                            <div class="progress_bg">
                                <div class="progress_bar"></div>
                            </div>
                        </div>
                        <div class="social-links">
                            <!--Social links-->
                            <a href="https://www.facebook.com/" target="_blank">
                                <i class="fa fa-facebook"></i>
                            </a>
                            <a href="https://twitter.com/" target="_blank">
                                <i class="fa fa-twitter"></i>
                            </a>
                            <a href="https://plus.google.com/" target="_blank">
                                <i class="fa fa-google"></i>
                            </a>
                            <a href="https://www.dribbble.com" target="_blank">
                                <i class="fa fa-dribbble"></i>
                            </a>
                        </div>
                    </div>
                    <!--.skills-->
                    <div class="about_btns animated animated_scroll fadeInUp" style="animation-delay: 0.3s">
                        <a href="{{ url_for('main.contact') }}" class="smooth_scroll">Contact Me</a>
                    </div>
                </div><!--.col-sm-7-->
            </div><!--.row-->
        </div><!--.container-->
    </section>
    <!--End About Section-->

    <!--Start Services Section-->
    <section class="services padding-top-90 padding-bottom-90 primary_bg" id="services">
        <div class="container">
            <div class="sec_title">
                <h2>services</h2>
            </div>

            <div class="row">
                
                <!--Service 1-->
                <div class="col-md-3 col-sm-6 item animated animated_scroll fadeInUp" style="animation-delay: 0.3s">
                    <div class="content">
                        <div class="icon">
                            <i class="fa fa-camera"></i>
                        </div>
                        <h3>Photography</h3>
                        <p>capture the beauty of life itself.</p>
                    </div>
                </div>
                
                <!--Service 2-->
                <div class="col-md-3 col-sm-6 item animated animated_scroll fadeInUp" style="animation-delay: 0.6s">
                    <div class="content">
                        <div class="icon">
                            <i class="fa fa-pencil-square"></i>
                        </div>
                        <h3>Edition</h3>
                        <p>Perceive details that make a difference.</p>
                    </div>
                </div>

                <!--Service 3-->
                <div class="col-md-3 col-sm-6 item animated animated_scroll fadeInUp" style="animation-delay: 0.9s">
                    <div class="content">
                        <div class="icon">
                            <i class="fa fa-video-camera"></i>
                        </div>
                        <h3>Video</h3>
                        <p>Remember every moment as if it were the last.</p>
                    </div>
                </div>
                
                <!--Service 4-->
                <div class="col-md-3 col-sm-6 item animated animated_scroll fadeInUp" style="animation-delay: 1.2s">
                    <div class="content">
                        <div class="icon">
                            <i class="fa fa-microphone"></i>
                        </div>
                        <h3>Audio Recording</h3>
                        <p>Hear what the world wants to tell us.</p>
                    </div>
                </div>
                
            </div><!--.row-->
        </div><!--.container-->
    </section>
    <!--End Services Section-->
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="zxx">
    <head>
        <!-- META DATA -->
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- TITLE OF SITE -->
        <title>Julian R. Studio</title>

        <!-- favicon -->
        <link id="favicon" rel="icon" type="image/png" href="{{ url_for('static', filename = 'images/favicon.ico') }}">

        <!-- Google Fonts-->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500%7CMontserrat:300,400,500,600,700,800,900">

        <!-- Bootstrap css -->
        <link rel="stylesheet" href=" {{ url_for('static', filename = 'css/bootstrap.css') }}">

        <!-- animate.css -->
        <link rel="stylesheet" href=" {{ url_for('static', filename = 'css/animate.css') }}">

        <!-- magnific-popup.css -->
        <link rel="stylesheet" href=" {{ url_for('static', filename = 'css/magnific-popup.css') }}">

        <!-- owl carousel css -->
        <link rel="stylesheet" href=" {{ url_for('static', filename = 'css/owl.carousel.min.css') }}">
        <link rel="stylesheet" href=" {{ url_for('static', filename = 'css/owl.theme.min.css') }}">

        <!-- font-awesome.min.css -->
        <link rel="stylesheet" href=" {{ url_for('static', filename = 'css/font-awesome.min.css') }}">
        
        <!-- Main style css -->
        <link rel="stylesheet" href=" {{ url_for('static', filename = 'css/style.css') }}">
        
        <!-- Responsive css -->
        <link rel="stylesheet" href=" {{ url_for('static', filename = 'css/responsive.css') }}">
         
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body data-spy="scroll" data-target=".navbar" data-offset="70">

        <!--Start Preloader-->
        <div class="page-loader startLoad">
          <div class="loader startLoad"></div>
        </div>
        <!--End Preloader-->

        <!--Start Scroll Top-->
        <div class="top">
            <a href="#home" class="smooth_scroll"><i class="fa fa-angle-up fa-2x"></i></a>
        </div>
        <!--End Scroll Top-->

        <!--Start Home Section-->
        <section class="home" id="home">
            {% block navbar %}
            {% endblock %}
        </section>
        <!--End Home Section-->

        {% block content %}
        {% endblock %}

        <!--Start Footer-->
        <footer class="padding-top-90 padding-bottom-90">
            <div class="container text-center animated animated_scroll fadeInUp" style="animation-delay: 0.3s">
                <h3>Julian R Studio</h3>

                <div class="social-links">
                    <!--Social links-->
                    <a href="https://www.facebook.com/" target="_blank">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a href="https://twitter.com/" target="_blank">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a href="https://plus.google.com/" target="_blank">
                        <i class="fa fa-google"></i>
                    </a>
                    <a href="https://www.dribbble.com" target="_blank">
                        <i class="fa fa-dribbble"></i>
                    </a>
                </div>
                <p>&copy; Alejandro Gomez | All rights reserved.</p>
            </div><!--.container-->  
        </footer>
        <!--End Footer-->

        <!--jquery.min.js-->
        <script src="{{ url_for('static', filename = 'js/jquery.min.js') }}"></script>

        <!--parallax.min.js-->
        <script src="{{ url_for('static', filename = 'js/parallax.min.js') }}"></script>

        <!--animate-skills.js-->
        <script src="{{ url_for('static', filename = 'js/animate-skills.js') }}"></script>

        <!--jquery.fittext.js-->
        <script src="{{ url_for('static', filename = 'js/jquery.fittext.js') }}"></script>

        <!--bootstrap.min.js-->
        <script src="{{ url_for('static', filename = 'js/bootstrap.min.js') }}"></script>

        <!--typed.min.js-->
        <script src="{{ url_for('static', filename = 'js/typed.min.js') }}"></script>

        <!--particles.min.js-->
        <script src="{{ url_for('static', filename = 'js/particles.min.js') }}"></script>

        <!--app.js-->
        <script src="{{ url_for('static', filename = 'js/app.js') }}"></script>

        <!--jquery.magnific-popup.min.js-->
        <script src="{{ url_for('static', filename = 'js/jquery.magnific-popup.min.js') }}"></script>

        <!--isotope.pkgd.min.js-->
        <script src="{{ url_for('static', filename = 'js/isotope.pkgd.min.js') }}"></script>

        <!--owl.carousel.min.js-->
        <script src="{{ url_for('static', filename = 'js/owl.carousel.min.js') }}"></script>

        <!-- Main script js -->
        <script src="{{ url_for('static', filename = 'js/custom.js') }}"></script>

    </body>
</html>

app/templates/contact.html
{% extends "base.html" %}

{% block navbar %}
    <!-- nav -->
    <nav class="navbar navbar-default navbar-fixed-top" style="background-color: #000;">
        <div class="container">
            <div class="navbar-header"> 
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- LOGO -->
                <a class="navbar-brand" href="#">JULIAN RODRIGUEZ</a>

            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('main.index') }}" class="smooth_scroll">Home</a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.about') }}" class="smooth_scroll">About</a>
                    </li>                        
                    <li>
                        <a href="{{ url_for('main.contact') }}" class="smooth_scroll">Contact</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!--.container-->
    </nav>
{% endblock %}

{% block content %}
    <!-- Map section -->
    <section class="map padding-top-90" >
        <div class="container-fluid">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3026.0439281449776!2d-111.9540196851859!3d40.673001047938534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87528b8806a80917%3A0x46b140af4b3fe120!2s4480%20Edgeware%20Ln%2C%20Salt%20Lake%20City%2C%20UT%2084119!5e0!3m2!1sen!2sus!4v1604426025627!5m2!1sen!2sus" width="100%" height="400" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </div>
    </section>
    <!-- End Map Section -->
    <!--Start Contact Section-->
    <section class="contact padding-top-90 padding-bottom-90 primary_bg" id="contact">
        <div class="container">
            <div class="sec_title">
                <h2>Contact</h2>
            </div>

            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="row text-center info animated animated_scroll fadeInUp" style="animation-delay: 0.3s">

                        <div class="col-sm-4">
                            <div class="content">
                                <span class="fa fa-phone"></span>
                                <div>
                                    <h4>Call Me</h4>
                                    <p>+1(801)8605832</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="content">
                                <span class="fa fa-envelope"></span>
                                <div>
                                    <h4>Mail Me</h4>
                                    <p><a href="mailto:ph.julianrd@gmail.com">ph.julianrd@gmail.com</a></p>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="content">
                                <span class="fa fa-map-marker"></span>
                                <div>
                                    <h4>Find Me</h4>
                                    <p>Salt lake city, UT</p>
                                </div>
                            </div>
                        </div>

                    </div><!--.row-->
                        
                    <div class="contact_form animated animated_scroll fadeInUp" style="animation-delay: 0.4s">
                        <form action="/Send-contact" id="contact" method="post">
                            <input placeholder="Name" name="name" type="text" class="form-control">
                            <input placeholder="Last Name" name="lastname" type="text" class="form-control">
                            <input placeholder="Phone Number" name="Phone" type="text" class="form-control">
                            <input placeholder="E-mail" name="email" type="email" class="form-control">
                            <textarea placeholder="Message" name="message" class="form-control"></textarea>
                            <div class="submit btn">send message</div>
                            <!--Contact form message-->
                            <div class="msg_success"><p>Your message has been sent. Thank you!</p></div>
                            <div class="msg_error"><p>Sorry your message can not be sent.</p></div>
                            <!--End contact form message-->
                        </form>
                    </div>
                </div><!--.col-md-10-->
            </div><!--.row-->
        </div><!--.container-->    
    </section>
    <!--End Contact Section-->
{% endblock %}

app/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email</title>
</head>
<body>
    {{ email_data }}
</body>
</html>